# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/peter/Documents/Uni/Prog/02 Semester/Prog pr/DuckHunter"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/peter/Documents/Uni/Prog/02 Semester/Prog pr/DuckHunter"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/peter/Documents/Uni/Prog/02 Semester/Prog pr/DuckHunter/CMakeFiles" "/home/peter/Documents/Uni/Prog/02 Semester/Prog pr/DuckHunter//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/peter/Documents/Uni/Prog/02 Semester/Prog pr/DuckHunter/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asciigfx

# Build rule for target.
asciigfx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asciigfx
.PHONY : asciigfx

# fast build rule for target.
asciigfx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/build
.PHONY : asciigfx/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

ammo.o: ammo.cpp.o
.PHONY : ammo.o

# target to build an object file
ammo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ammo.cpp.o
.PHONY : ammo.cpp.o

ammo.i: ammo.cpp.i
.PHONY : ammo.i

# target to preprocess a source file
ammo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ammo.cpp.i
.PHONY : ammo.cpp.i

ammo.s: ammo.cpp.s
.PHONY : ammo.s

# target to generate assembly for a file
ammo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ammo.cpp.s
.PHONY : ammo.cpp.s

ascii-gfx/gfx/gfx.o: ascii-gfx/gfx/gfx.cpp.o
.PHONY : ascii-gfx/gfx/gfx.o

# target to build an object file
ascii-gfx/gfx/gfx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gfx.cpp.o
.PHONY : ascii-gfx/gfx/gfx.cpp.o

ascii-gfx/gfx/gfx.i: ascii-gfx/gfx/gfx.cpp.i
.PHONY : ascii-gfx/gfx/gfx.i

# target to preprocess a source file
ascii-gfx/gfx/gfx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gfx.cpp.i
.PHONY : ascii-gfx/gfx/gfx.cpp.i

ascii-gfx/gfx/gfx.s: ascii-gfx/gfx/gfx.cpp.s
.PHONY : ascii-gfx/gfx/gfx.s

# target to generate assembly for a file
ascii-gfx/gfx/gfx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gfx.cpp.s
.PHONY : ascii-gfx/gfx/gfx.cpp.s

ascii-gfx/gfx/gridarea.o: ascii-gfx/gfx/gridarea.cpp.o
.PHONY : ascii-gfx/gfx/gridarea.o

# target to build an object file
ascii-gfx/gfx/gridarea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridarea.cpp.o
.PHONY : ascii-gfx/gfx/gridarea.cpp.o

ascii-gfx/gfx/gridarea.i: ascii-gfx/gfx/gridarea.cpp.i
.PHONY : ascii-gfx/gfx/gridarea.i

# target to preprocess a source file
ascii-gfx/gfx/gridarea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridarea.cpp.i
.PHONY : ascii-gfx/gfx/gridarea.cpp.i

ascii-gfx/gfx/gridarea.s: ascii-gfx/gfx/gridarea.cpp.s
.PHONY : ascii-gfx/gfx/gridarea.s

# target to generate assembly for a file
ascii-gfx/gfx/gridarea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridarea.cpp.s
.PHONY : ascii-gfx/gfx/gridarea.cpp.s

ascii-gfx/gfx/gridfont.o: ascii-gfx/gfx/gridfont.cpp.o
.PHONY : ascii-gfx/gfx/gridfont.o

# target to build an object file
ascii-gfx/gfx/gridfont.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridfont.cpp.o
.PHONY : ascii-gfx/gfx/gridfont.cpp.o

ascii-gfx/gfx/gridfont.i: ascii-gfx/gfx/gridfont.cpp.i
.PHONY : ascii-gfx/gfx/gridfont.i

# target to preprocess a source file
ascii-gfx/gfx/gridfont.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridfont.cpp.i
.PHONY : ascii-gfx/gfx/gridfont.cpp.i

ascii-gfx/gfx/gridfont.s: ascii-gfx/gfx/gridfont.cpp.s
.PHONY : ascii-gfx/gfx/gridfont.s

# target to generate assembly for a file
ascii-gfx/gfx/gridfont.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridfont.cpp.s
.PHONY : ascii-gfx/gfx/gridfont.cpp.s

ascii-gfx/gfx/gridmenu.o: ascii-gfx/gfx/gridmenu.cpp.o
.PHONY : ascii-gfx/gfx/gridmenu.o

# target to build an object file
ascii-gfx/gfx/gridmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridmenu.cpp.o
.PHONY : ascii-gfx/gfx/gridmenu.cpp.o

ascii-gfx/gfx/gridmenu.i: ascii-gfx/gfx/gridmenu.cpp.i
.PHONY : ascii-gfx/gfx/gridmenu.i

# target to preprocess a source file
ascii-gfx/gfx/gridmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridmenu.cpp.i
.PHONY : ascii-gfx/gfx/gridmenu.cpp.i

ascii-gfx/gfx/gridmenu.s: ascii-gfx/gfx/gridmenu.cpp.s
.PHONY : ascii-gfx/gfx/gridmenu.s

# target to generate assembly for a file
ascii-gfx/gfx/gridmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/gridmenu.cpp.s
.PHONY : ascii-gfx/gfx/gridmenu.cpp.s

ascii-gfx/gfx/joystick.o: ascii-gfx/gfx/joystick.cpp.o
.PHONY : ascii-gfx/gfx/joystick.o

# target to build an object file
ascii-gfx/gfx/joystick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/joystick.cpp.o
.PHONY : ascii-gfx/gfx/joystick.cpp.o

ascii-gfx/gfx/joystick.i: ascii-gfx/gfx/joystick.cpp.i
.PHONY : ascii-gfx/gfx/joystick.i

# target to preprocess a source file
ascii-gfx/gfx/joystick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/joystick.cpp.i
.PHONY : ascii-gfx/gfx/joystick.cpp.i

ascii-gfx/gfx/joystick.s: ascii-gfx/gfx/joystick.cpp.s
.PHONY : ascii-gfx/gfx/joystick.s

# target to generate assembly for a file
ascii-gfx/gfx/joystick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/joystick.cpp.s
.PHONY : ascii-gfx/gfx/joystick.cpp.s

ascii-gfx/gfx/math2d.o: ascii-gfx/gfx/math2d.cpp.o
.PHONY : ascii-gfx/gfx/math2d.o

# target to build an object file
ascii-gfx/gfx/math2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/math2d.cpp.o
.PHONY : ascii-gfx/gfx/math2d.cpp.o

ascii-gfx/gfx/math2d.i: ascii-gfx/gfx/math2d.cpp.i
.PHONY : ascii-gfx/gfx/math2d.i

# target to preprocess a source file
ascii-gfx/gfx/math2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/math2d.cpp.i
.PHONY : ascii-gfx/gfx/math2d.cpp.i

ascii-gfx/gfx/math2d.s: ascii-gfx/gfx/math2d.cpp.s
.PHONY : ascii-gfx/gfx/math2d.s

# target to generate assembly for a file
ascii-gfx/gfx/math2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/math2d.cpp.s
.PHONY : ascii-gfx/gfx/math2d.cpp.s

ascii-gfx/gfx/mouse.o: ascii-gfx/gfx/mouse.cpp.o
.PHONY : ascii-gfx/gfx/mouse.o

# target to build an object file
ascii-gfx/gfx/mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/mouse.cpp.o
.PHONY : ascii-gfx/gfx/mouse.cpp.o

ascii-gfx/gfx/mouse.i: ascii-gfx/gfx/mouse.cpp.i
.PHONY : ascii-gfx/gfx/mouse.i

# target to preprocess a source file
ascii-gfx/gfx/mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/mouse.cpp.i
.PHONY : ascii-gfx/gfx/mouse.cpp.i

ascii-gfx/gfx/mouse.s: ascii-gfx/gfx/mouse.cpp.s
.PHONY : ascii-gfx/gfx/mouse.s

# target to generate assembly for a file
ascii-gfx/gfx/mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/mouse.cpp.s
.PHONY : ascii-gfx/gfx/mouse.cpp.s

ascii-gfx/gfx/polygon.o: ascii-gfx/gfx/polygon.cpp.o
.PHONY : ascii-gfx/gfx/polygon.o

# target to build an object file
ascii-gfx/gfx/polygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/polygon.cpp.o
.PHONY : ascii-gfx/gfx/polygon.cpp.o

ascii-gfx/gfx/polygon.i: ascii-gfx/gfx/polygon.cpp.i
.PHONY : ascii-gfx/gfx/polygon.i

# target to preprocess a source file
ascii-gfx/gfx/polygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/polygon.cpp.i
.PHONY : ascii-gfx/gfx/polygon.cpp.i

ascii-gfx/gfx/polygon.s: ascii-gfx/gfx/polygon.cpp.s
.PHONY : ascii-gfx/gfx/polygon.s

# target to generate assembly for a file
ascii-gfx/gfx/polygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/polygon.cpp.s
.PHONY : ascii-gfx/gfx/polygon.cpp.s

ascii-gfx/gfx/scrollarea.o: ascii-gfx/gfx/scrollarea.cpp.o
.PHONY : ascii-gfx/gfx/scrollarea.o

# target to build an object file
ascii-gfx/gfx/scrollarea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/scrollarea.cpp.o
.PHONY : ascii-gfx/gfx/scrollarea.cpp.o

ascii-gfx/gfx/scrollarea.i: ascii-gfx/gfx/scrollarea.cpp.i
.PHONY : ascii-gfx/gfx/scrollarea.i

# target to preprocess a source file
ascii-gfx/gfx/scrollarea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/scrollarea.cpp.i
.PHONY : ascii-gfx/gfx/scrollarea.cpp.i

ascii-gfx/gfx/scrollarea.s: ascii-gfx/gfx/scrollarea.cpp.s
.PHONY : ascii-gfx/gfx/scrollarea.s

# target to generate assembly for a file
ascii-gfx/gfx/scrollarea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/scrollarea.cpp.s
.PHONY : ascii-gfx/gfx/scrollarea.cpp.s

ascii-gfx/gfx/sound.o: ascii-gfx/gfx/sound.cpp.o
.PHONY : ascii-gfx/gfx/sound.o

# target to build an object file
ascii-gfx/gfx/sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/sound.cpp.o
.PHONY : ascii-gfx/gfx/sound.cpp.o

ascii-gfx/gfx/sound.i: ascii-gfx/gfx/sound.cpp.i
.PHONY : ascii-gfx/gfx/sound.i

# target to preprocess a source file
ascii-gfx/gfx/sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/sound.cpp.i
.PHONY : ascii-gfx/gfx/sound.cpp.i

ascii-gfx/gfx/sound.s: ascii-gfx/gfx/sound.cpp.s
.PHONY : ascii-gfx/gfx/sound.s

# target to generate assembly for a file
ascii-gfx/gfx/sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/sound.cpp.s
.PHONY : ascii-gfx/gfx/sound.cpp.s

ascii-gfx/gfx/util.o: ascii-gfx/gfx/util.cpp.o
.PHONY : ascii-gfx/gfx/util.o

# target to build an object file
ascii-gfx/gfx/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/util.cpp.o
.PHONY : ascii-gfx/gfx/util.cpp.o

ascii-gfx/gfx/util.i: ascii-gfx/gfx/util.cpp.i
.PHONY : ascii-gfx/gfx/util.i

# target to preprocess a source file
ascii-gfx/gfx/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/util.cpp.i
.PHONY : ascii-gfx/gfx/util.cpp.i

ascii-gfx/gfx/util.s: ascii-gfx/gfx/util.cpp.s
.PHONY : ascii-gfx/gfx/util.s

# target to generate assembly for a file
ascii-gfx/gfx/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asciigfx.dir/build.make CMakeFiles/asciigfx.dir/ascii-gfx/gfx/util.cpp.s
.PHONY : ascii-gfx/gfx/util.cpp.s

bird.o: bird.cpp.o
.PHONY : bird.o

# target to build an object file
bird.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bird.cpp.o
.PHONY : bird.cpp.o

bird.i: bird.cpp.i
.PHONY : bird.i

# target to preprocess a source file
bird.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bird.cpp.i
.PHONY : bird.cpp.i

bird.s: bird.cpp.s
.PHONY : bird.s

# target to generate assembly for a file
bird.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bird.cpp.s
.PHONY : bird.cpp.s

gameloop.o: gameloop.cpp.o
.PHONY : gameloop.o

# target to build an object file
gameloop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gameloop.cpp.o
.PHONY : gameloop.cpp.o

gameloop.i: gameloop.cpp.i
.PHONY : gameloop.i

# target to preprocess a source file
gameloop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gameloop.cpp.i
.PHONY : gameloop.cpp.i

gameloop.s: gameloop.cpp.s
.PHONY : gameloop.s

# target to generate assembly for a file
gameloop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gameloop.cpp.s
.PHONY : gameloop.cpp.s

gamestate.o: gamestate.cpp.o
.PHONY : gamestate.o

# target to build an object file
gamestate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gamestate.cpp.o
.PHONY : gamestate.cpp.o

gamestate.i: gamestate.cpp.i
.PHONY : gamestate.i

# target to preprocess a source file
gamestate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gamestate.cpp.i
.PHONY : gamestate.cpp.i

gamestate.s: gamestate.cpp.s
.PHONY : gamestate.s

# target to generate assembly for a file
gamestate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gamestate.cpp.s
.PHONY : gamestate.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

msleep.o: msleep.cpp.o
.PHONY : msleep.o

# target to build an object file
msleep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/msleep.cpp.o
.PHONY : msleep.cpp.o

msleep.i: msleep.cpp.i
.PHONY : msleep.i

# target to preprocess a source file
msleep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/msleep.cpp.i
.PHONY : msleep.cpp.i

msleep.s: msleep.cpp.s
.PHONY : msleep.s

# target to generate assembly for a file
msleep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/msleep.cpp.s
.PHONY : msleep.cpp.s

score.o: score.cpp.o
.PHONY : score.o

# target to build an object file
score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/score.cpp.o
.PHONY : score.cpp.o

score.i: score.cpp.i
.PHONY : score.i

# target to preprocess a source file
score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/score.cpp.i
.PHONY : score.cpp.i

score.s: score.cpp.s
.PHONY : score.s

# target to generate assembly for a file
score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/score.cpp.s
.PHONY : score.cpp.s

windmill.o: windmill.cpp.o
.PHONY : windmill.o

# target to build an object file
windmill.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/windmill.cpp.o
.PHONY : windmill.cpp.o

windmill.i: windmill.cpp.i
.PHONY : windmill.i

# target to preprocess a source file
windmill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/windmill.cpp.i
.PHONY : windmill.cpp.i

windmill.s: windmill.cpp.s
.PHONY : windmill.s

# target to generate assembly for a file
windmill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/windmill.cpp.s
.PHONY : windmill.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asciigfx"
	@echo "... main"
	@echo "... ammo.o"
	@echo "... ammo.i"
	@echo "... ammo.s"
	@echo "... ascii-gfx/gfx/gfx.o"
	@echo "... ascii-gfx/gfx/gfx.i"
	@echo "... ascii-gfx/gfx/gfx.s"
	@echo "... ascii-gfx/gfx/gridarea.o"
	@echo "... ascii-gfx/gfx/gridarea.i"
	@echo "... ascii-gfx/gfx/gridarea.s"
	@echo "... ascii-gfx/gfx/gridfont.o"
	@echo "... ascii-gfx/gfx/gridfont.i"
	@echo "... ascii-gfx/gfx/gridfont.s"
	@echo "... ascii-gfx/gfx/gridmenu.o"
	@echo "... ascii-gfx/gfx/gridmenu.i"
	@echo "... ascii-gfx/gfx/gridmenu.s"
	@echo "... ascii-gfx/gfx/joystick.o"
	@echo "... ascii-gfx/gfx/joystick.i"
	@echo "... ascii-gfx/gfx/joystick.s"
	@echo "... ascii-gfx/gfx/math2d.o"
	@echo "... ascii-gfx/gfx/math2d.i"
	@echo "... ascii-gfx/gfx/math2d.s"
	@echo "... ascii-gfx/gfx/mouse.o"
	@echo "... ascii-gfx/gfx/mouse.i"
	@echo "... ascii-gfx/gfx/mouse.s"
	@echo "... ascii-gfx/gfx/polygon.o"
	@echo "... ascii-gfx/gfx/polygon.i"
	@echo "... ascii-gfx/gfx/polygon.s"
	@echo "... ascii-gfx/gfx/scrollarea.o"
	@echo "... ascii-gfx/gfx/scrollarea.i"
	@echo "... ascii-gfx/gfx/scrollarea.s"
	@echo "... ascii-gfx/gfx/sound.o"
	@echo "... ascii-gfx/gfx/sound.i"
	@echo "... ascii-gfx/gfx/sound.s"
	@echo "... ascii-gfx/gfx/util.o"
	@echo "... ascii-gfx/gfx/util.i"
	@echo "... ascii-gfx/gfx/util.s"
	@echo "... bird.o"
	@echo "... bird.i"
	@echo "... bird.s"
	@echo "... gameloop.o"
	@echo "... gameloop.i"
	@echo "... gameloop.s"
	@echo "... gamestate.o"
	@echo "... gamestate.i"
	@echo "... gamestate.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msleep.o"
	@echo "... msleep.i"
	@echo "... msleep.s"
	@echo "... score.o"
	@echo "... score.i"
	@echo "... score.s"
	@echo "... windmill.o"
	@echo "... windmill.i"
	@echo "... windmill.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

